import './styles.css';
import Graph from 'graphology';
import Sigma from 'sigma';
import { supabase, supabaseConfigured } from './lib/supabase.js';
import { uploadPrivateEvidence } from './lib/storage.js';
import { graphMetrics } from './lib/analysis.js';

const translations = {
  en: {
    product: 'NETRAKSHAK', productSub: 'Criminal Network Analysis', restricted: 'RESTRICTED ACCESS',
    signInTitle: 'Secure investigator sign-in', signInBody: 'Access is monitored and every evidence action is recorded.', email: 'Official email', password: 'Password', signIn: 'Sign in', demoHint: 'Prototype access: use any email and password.',
    command: 'Command centre', network: 'Network graph', fir: 'FIR intake', sources: 'Data & integrity', settings: 'Settings', overview: 'Overview', search: 'Search entities, FIR numbers, phones, vehicles…', activeCase: 'Active investigation', systemStatus: 'SYSTEM STATUS', secure: 'Secure • audit online', today: 'Today', alerts: 'Priority alerts', entities: 'Entities under review', connections: 'Verified connections', integrity: 'Evidence integrity', viewNetwork: 'Open network', reviewFIR: 'Review FIR intake', high: 'High', medium: 'Medium', low: 'Low', risk: 'Risk', type: 'Type', connectionsSort: 'Connections', recent: 'Recent activity', name: 'Name', allTypes: 'All types', filter: 'Filter', fullscreen: 'Fullscreen', exitFullscreen: 'Exit fullscreen', zoomIn: 'Zoom in', zoomOut: 'Zoom out', reset: 'Reset view', graphHint: 'Drag nodes • scroll to zoom • select an entity to inspect', selectedEntity: 'Selected entity', associations: 'Associations', linkedEvents: 'Linked events', source: 'Source', confidence: 'Confidence', evidenceTrail: 'Evidence trail', uploadTitle: 'FIR document intake', uploadBody: 'Drop a scanned FIR here or browse a local file. The original is fingerprinted before processing.', browse: 'Browse file', fingerprint: 'SHA-256 fingerprint', ocrReady: 'OCR adapter ready for connection', reviewDraft: 'Review extracted draft', noFile: 'No document selected', auditTitle: 'Tamper-evident audit trail', auditBody: 'Every change is versioned and hash-linked. Ledger anchoring is ready for deployment.', verified: 'Verified', imported: 'Imported', synthetic: 'Synthetic demo data', live: 'Live source', dataSources: 'Data sources', integrityChecks: 'Integrity checks', hashChain: 'Hash chain', ledger: 'Ledger anchor', all: 'All', logout: 'Sign out', language: 'Language', welcome: 'Good morning, Officer.', briefing: 'Here is your network briefing for today.', viewAll: 'View all', noResults: 'No matching entities', sourceNote: 'Prototype data is synthetic and labelled. Connect the NCRB-approved dataset to enable live case analysis.'
  },
  hi: { product: 'नेत्ररक्षक', productSub: 'अपराध नेटवर्क विश्लेषण', restricted: 'सीमित प्रवेश', signInTitle: 'सुरक्षित अन्वेषक प्रवेश', signInBody: 'प्रवेश की निगरानी की जाती है और हर साक्ष्य कार्रवाई दर्ज होती है।', email: 'आधिकारिक ईमेल', password: 'पासवर्ड', signIn: 'प्रवेश करें', demoHint: 'प्रोटोटाइप: कोई भी ईमेल और पासवर्ड इस्तेमाल करें।', command: 'कमांड सेंटर', network: 'नेटवर्क ग्राफ', fir: 'एफआईआर इनटेक', sources: 'डेटा और अखंडता', settings: 'सेटिंग्स', overview: 'अवलोकन', search: 'इकाई, एफआईआर नंबर, फोन, वाहन खोजें…', activeCase: 'सक्रिय जांच', systemStatus: 'सिस्टम स्थिति', secure: 'सुरक्षित • ऑडिट ऑनलाइन', today: 'आज', alerts: 'प्राथमिकता अलर्ट', entities: 'समीक्षा वाली इकाइयां', connections: 'सत्यापित कनेक्शन', integrity: 'साक्ष्य अखंडता', viewNetwork: 'नेटवर्क खोलें', reviewFIR: 'एफआईआर देखें', high: 'उच्च', medium: 'मध्यम', low: 'कम', risk: 'जोखिम', type: 'प्रकार', connectionsSort: 'कनेक्शन', recent: 'हाल की गतिविधि', name: 'नाम', allTypes: 'सभी प्रकार', filter: 'फ़िल्टर', fullscreen: 'फुलस्क्रीन', exitFullscreen: 'बाहर निकलें', zoomIn: 'ज़ूम इन', zoomOut: 'ज़ूम आउट', reset: 'रीसेट', graphHint: 'नोड खींचें • ज़ूम के लिए स्क्रॉल करें • जांच हेतु इकाई चुनें', selectedEntity: 'चयनित इकाई', associations: 'संबंध', linkedEvents: 'जुड़ी घटनाएं', source: 'स्रोत', confidence: 'विश्वास', evidenceTrail: 'साक्ष्य ट्रेल', uploadTitle: 'एफआईआर दस्तावेज़ इनटेक', uploadBody: 'स्कैन की गई एफआईआर यहां छोड़ें या स्थानीय फाइल चुनें। प्रोसेसिंग से पहले फिंगरप्रिंट बनेगा।', browse: 'फाइल चुनें', fingerprint: 'SHA-256 फिंगरप्रिंट', ocrReady: 'OCR एडाप्टर कनेक्शन के लिए तैयार', reviewDraft: 'निकाले गए ड्राफ्ट की समीक्षा', noFile: 'कोई दस्तावेज़ नहीं चुना', auditTitle: 'छेड़छाड़-रोधी ऑडिट ट्रेल', auditBody: 'हर बदलाव संस्करणित और हैश-लिंक्ड है। लेजर एंकरिंग तैयार है।', verified: 'सत्यापित', imported: 'आयातित', synthetic: 'सिंथेटिक डेमो डेटा', live: 'लाइव स्रोत', dataSources: 'डेटा स्रोत', integrityChecks: 'अखंडता जांच', hashChain: 'हैश चेन', ledger: 'लेजर एंकर', all: 'सभी', logout: 'बाहर निकलें', language: 'भाषा', welcome: 'सुप्रभात, अधिकारी।', briefing: 'आज का नेटवर्क ब्रीफिंग यहां है।', viewAll: 'सभी देखें', noResults: 'कोई मिलती इकाई नहीं', sourceNote: 'प्रोटोटाइप डेटा सिंथेटिक और लेबल किया हुआ है। लाइव केस विश्लेषण के लिए NCRB-अनुमोदित डेटासेट जोड़ें।' },
  mr: { product: 'नेत्ररक्षक', productSub: 'गुन्हेगारी नेटवर्क विश्लेषण', restricted: 'मर्यादित प्रवेश', signInTitle: 'सुरक्षित तपासनीस प्रवेश', signInBody: 'प्रवेशाचे निरीक्षण केले जाते आणि प्रत्येक पुरावा कृती नोंदवली जाते.', email: 'अधिकृत ईमेल', password: 'पासवर्ड', signIn: 'प्रवेश करा', demoHint: 'प्रोटोटाइप: कोणताही ईमेल आणि पासवर्ड वापरा.', command: 'कमांड सेंटर', network: 'नेटवर्क ग्राफ', fir: 'FIR इनटेक', sources: 'डेटा आणि अखंडता', settings: 'सेटिंग्ज', overview: 'आढावा', search: 'संस्था, FIR क्रमांक, फोन, वाहन शोधा…', activeCase: 'सक्रिय तपास', systemStatus: 'सिस्टम स्थिती', secure: 'सुरक्षित • ऑडिट ऑनलाइन', today: 'आज', alerts: 'प्राधान्य अलर्ट', entities: 'तपासणीतील संस्था', connections: 'सत्यापित कनेक्शन', integrity: 'पुरावा अखंडता', viewNetwork: 'नेटवर्क उघडा', reviewFIR: 'FIR तपासा', high: 'उच्च', medium: 'मध्यम', low: 'कमी', risk: 'धोका', type: 'प्रकार', connectionsSort: 'कनेक्शन', recent: 'अलीकडील कृती', name: 'नाव', allTypes: 'सर्व प्रकार', filter: 'फिल्टर', fullscreen: 'फुलस्क्रीन', exitFullscreen: 'बाहेर पडा', zoomIn: 'झूम इन', zoomOut: 'झूम आउट', reset: 'रीसेट', graphHint: 'नोड ओढा • झूम करण्यासाठी स्क्रोल करा • तपासणीसाठी संस्था निवडा', selectedEntity: 'निवडलेली संस्था', associations: 'संबंध', linkedEvents: 'जोडलेल्या घटना', source: 'स्रोत', confidence: 'विश्वास', evidenceTrail: 'पुरावा ट्रेल', uploadTitle: 'FIR दस्तऐवज इनटेक', uploadBody: 'स्कॅन केलेली FIR येथे टाका किंवा स्थानिक फाइल निवडा. प्रक्रियेपूर्वी फिंगरप्रिंट तयार होईल.', browse: 'फाइल निवडा', fingerprint: 'SHA-256 फिंगरप्रिंट', ocrReady: 'OCR अडॅप्टर जोडणीसाठी तयार', reviewDraft: 'काढलेल्या ड्राफ्टचे पुनरावलोकन', noFile: 'दस्तऐवज निवडलेला नाही', auditTitle: 'छेडछाड-प्रतिरोधक ऑडिट ट्रेल', auditBody: 'प्रत्येक बदल आवृत्तीबद्ध आणि हॅश-लिंक्ड आहे. लेजर अँकरिंग तयार आहे.', verified: 'सत्यापित', imported: 'आयातित', synthetic: 'सिंथेटिक डेमो डेटा', live: 'लाइव्ह स्रोत', dataSources: 'डेटा स्रोत', integrityChecks: 'अखंडता तपासणी', hashChain: 'हॅश चेन', ledger: 'लेजर अँकर', all: 'सर्व', logout: 'बाहेर पडा', language: 'भाषा', welcome: 'सुप्रभात, अधिकारी.', briefing: 'आजचे नेटवर्क ब्रीफिंग येथे आहे.', viewAll: 'सर्व पहा', noResults: 'जुळणारी संस्था नाही', sourceNote: 'प्रोटोटाइप डेटा सिंथेटिक आणि लेबल केलेला आहे. लाइव्ह केस विश्लेषणासाठी NCRB-अनुमोदित डेटासेट जोडा.' },
  gu: { product: 'નેત્રરક્ષક', productSub: 'ગુનાહિત નેટવર્ક વિશ્લેષણ', restricted: 'મર્યાદિત પ્રવેશ', signInTitle: 'સુરક્ષિત તપાસકર્તા પ્રવેશ', signInBody: 'પ્રવેશનું નિરીક્ષણ થાય છે અને દરેક પુરાવા ક્રિયા નોંધાય છે.', email: 'અધિકૃત ઈમેલ', password: 'પાસવર્ડ', signIn: 'સાઇન ઇન', demoHint: 'પ્રોટોટાઇપ: કોઈપણ ઈમેલ અને પાસવર્ડ વાપરો.', command: 'કમાન્ડ સેન્ટર', network: 'નેટવર્ક ગ્રાફ', fir: 'FIR ઇનટેક', sources: 'ડેટા અને અખંડિતતા', settings: 'સેટિંગ્સ', overview: 'ઝાંખી', search: 'એન્ટિટી, FIR નંબર, ફોન, વાહન શોધો…', activeCase: 'સક્રિય તપાસ', systemStatus: 'સિસ્ટમ સ્થિતિ', secure: 'સુરક્ષિત • ઓડિટ ઓનલાઇન', today: 'આજે', alerts: 'પ્રાથમિકતા એલર્ટ', entities: 'સમીક્ષા હેઠળની એન્ટિટી', connections: 'ચકાસેલા જોડાણો', integrity: 'પુરાવાની અખંડિતતા', viewNetwork: 'નેટવર્ક ખોલો', reviewFIR: 'FIR જુઓ', high: 'ઉચ્ચ', medium: 'મધ્યમ', low: 'નીચું', risk: 'જોખમ', type: 'પ્રકાર', connectionsSort: 'જોડાણો', recent: 'તાજેતરની પ્રવૃત્તિ', name: 'નામ', allTypes: 'બધા પ્રકાર', filter: 'ફિલ્ટર', fullscreen: 'ફુલસ્ક્રીન', exitFullscreen: 'બહાર નીકળો', zoomIn: 'ઝૂમ ઇન', zoomOut: 'ઝૂમ આઉટ', reset: 'રીસેટ', graphHint: 'નોડ ખેંચો • ઝૂમ માટે સ્ક્રોલ કરો • તપાસ માટે એન્ટિટી પસંદ કરો', selectedEntity: 'પસંદ કરેલી એન્ટિટી', associations: 'સંબંધો', linkedEvents: 'જોડાયેલી ઘટનાઓ', source: 'સ્રોત', confidence: 'વિશ્વાસ', evidenceTrail: 'પુરાવા ટ્રેલ', uploadTitle: 'FIR દસ્તાવેજ ઇનટેક', uploadBody: 'સ્કેન કરેલી FIR અહીં મૂકો અથવા સ્થાનિક ફાઇલ પસંદ કરો. પ્રક્રિયા પહેલાં ફિંગરપ્રિન્ટ બનશે.', browse: 'ફાઇલ પસંદ કરો', fingerprint: 'SHA-256 ફિંગરપ્રિન્ટ', ocrReady: 'OCR એડેપ્ટર જોડાણ માટે તૈયાર', reviewDraft: 'કાઢેલા ડ્રાફ્ટની સમીક્ષા', noFile: 'કોઈ દસ્તાવેજ પસંદ નથી', auditTitle: 'છેડછાડ-પ્રતિરોધક ઓડિટ ટ્રેલ', auditBody: 'દરેક ફેરફાર વર્ઝન અને હેશ-લિંક થયેલો છે. લેજર એન્કરિંગ તૈયાર છે.', verified: 'ચકાસેલ', imported: 'આયાત કરેલ', synthetic: 'સિંથેટિક ડેમો ડેટા', live: 'લાઇવ સ્રોત', dataSources: 'ડેટા સ્રોતો', integrityChecks: 'અખંડિતતા તપાસ', hashChain: 'હેશ ચેન', ledger: 'લેજર એન્કર', all: 'બધા', logout: 'સાઇન આઉટ', language: 'ભાષા', welcome: 'સુપ્રભાત, અધિકારી.', briefing: 'આજનું નેટવર્ક બ્રીફિંગ અહીં છે.', viewAll: 'બધું જુઓ', noResults: 'મેળ ખાતી એન્ટિટી નથી', sourceNote: 'પ્રોટોટાઇપ ડેટા સિન્થેટિક અને લેબલ કરેલો છે. લાઇવ કેસ વિશ્લેષણ માટે NCRB-મંજૂર ડેટાસેટ જોડો.' }
};

const extraTranslations = {
  en: { workspace:'Workspace', governance:'Governance', liveAudit:'Live audit stream', riskPulse:'Risk pulse', last30:'Last 30 days', sortBy:'Sort by', entitiesCount:'entities', prototypeEnvironment:'Prototype environment', priorityReview:'2 high priority · 1 review', sourceTypes:'Across 7 source types', lastVerified:'Last verified 09:42 IST', operationMonsoon:'Operation Monsoon', caseLocation:'Pune • Maharashtra • 18 connected entities', networkConfidence:'Network confidence', linkageAnalysis:'LINKAGE ANALYSIS • Operation Monsoon', documentIntelligence:'DOCUMENT INTELLIGENCE • NCRB WORKFLOW', uploadWorkflow:'Upload, fingerprint, extract, review, and save with an accountable chain of custody.', fingerprintStep:'Fingerprint', extractStep:'Extract', reviewStep:'Review', commitStep:'Commit', sha256:'SHA-256', ocrAdapter:'OCR adapter', officerConfirmation:'Officer confirmation', auditLedger:'Audit + ledger', reviewRequired:'Review is required before commit', importManifest:'Import manifest', sourceCatalogue:'GOVERNANCE • SOURCE CATALOGUE', sourceProvenance:'Every record has a declared source class, provenance, and integrity status.', batchVerified:'Last batch verification: 09:42 IST', permissionedReady:'Ready for permissioned deployment', anomalousExports:'0 anomalous exports', accessControls:'Access controls', investigatorProfile:'Investigator profile', responsibleAI:'Responsible AI controls', defaultLanguage:'Default language', dataEnvironment:'Data environment', mfaEnabled:'MFA enabled', liveAudit:'Live audit stream', investigationUnit:'Investigation Unit', officerName:'A. Sharma', tlsProtected:'TLS protected', ncrbWorkflow:'NCRB workflow', caseConfidence:'78%', approvedDataset:'NCRB-approved dataset', heroTitle:'See the network. Protect the evidence.', heroBody:'A secure intelligence workspace for connecting records, discovering patterns, and supporting investigators across India.', evidenceFirst:'Evidence-first investigations', graphPowered:'Graph-powered linkage analysis', auditableByDesign:'Auditable by design', prototypeFooter:'Netrakshak • SIH 2026 prototype', versionFooter:'v0.1 • Evidence integrity enabled', weeklyChange:'+8.4% this week', hashVerified:'Hash verified', entityMergeReview:'Entity merge review', assigned:'A. Sharma assigned', newLinkDetected:'New link detected', linkedAccount:'Account •• 9130 ↔ Arjun Pawar', datasetManifest:'Dataset manifest', demoBatch:'Synthetic demo batch v0.3', lastVerifiedTime:'Last verified 09:42 IST', riskDates:['15 Aug','22 Aug','29 Aug','05 Sep','12 Sep'], refreshed:'Risk pulse refreshed' },
  hi: { workspace:'कार्य क्षेत्र', governance:'प्रशासन', liveAudit:'लाइव ऑडिट स्ट्रीम', riskPulse:'जोखिम संकेत', last30:'पिछले 30 दिन', sortBy:'क्रमबद्ध करें', entitiesCount:'इकाइयां', prototypeEnvironment:'प्रोटोटाइप वातावरण', priorityReview:'2 उच्च प्राथमिकता · 1 समीक्षा', sourceTypes:'7 स्रोत प्रकारों में', lastVerified:'अंतिम सत्यापन 09:42 IST', operationMonsoon:'ऑपरेशन मॉनसून', caseLocation:'पुणे • महाराष्ट्र • 18 जुड़ी इकाइयां', networkConfidence:'नेटवर्क विश्वास', linkageAnalysis:'लिंकेज विश्लेषण • ऑपरेशन मॉनसून', documentIntelligence:'दस्तावेज़ इंटेलिजेंस • NCRB वर्कफ़्लो', uploadWorkflow:'जिम्मेदार चेन ऑफ कस्टडी के साथ अपलोड, फिंगरप्रिंट, एक्सट्रैक्ट, समीक्षा और सेव करें।', fingerprintStep:'फिंगरप्रिंट', extractStep:'निकालें', reviewStep:'समीक्षा', commitStep:'कमिट', sha256:'SHA-256', ocrAdapter:'OCR एडाप्टर', officerConfirmation:'अधिकारी पुष्टि', auditLedger:'ऑडिट + लेजर', reviewRequired:'कमिट से पहले समीक्षा आवश्यक है', importManifest:'मेनिफेस्ट आयात करें', sourceCatalogue:'प्रशासन • स्रोत सूची', sourceProvenance:'हर रिकॉर्ड में स्रोत वर्ग, प्रोवेनेंस और अखंडता स्थिति है।', batchVerified:'अंतिम बैच सत्यापन: 09:42 IST', permissionedReady:'परमिशन्ड तैनाती के लिए तैयार', anomalousExports:'0 असामान्य एक्सपोर्ट', accessControls:'प्रवेश नियंत्रण', investigatorProfile:'अन्वेषक प्रोफ़ाइल', responsibleAI:'जिम्मेदार AI नियंत्रण', defaultLanguage:'डिफ़ॉल्ट भाषा', dataEnvironment:'डेटा वातावरण', mfaEnabled:'MFA सक्षम', investigationUnit:'जांच इकाई', officerName:'ए. शर्मा', tlsProtected:'TLS सुरक्षित', ncrbWorkflow:'NCRB वर्कफ़्लो', caseConfidence:'78%', approvedDataset:'NCRB-अनुमोदित डेटासेट', heroTitle:'नेटवर्क देखें। साक्ष्य सुरक्षित रखें।', heroBody:'भारत भर के रिकॉर्ड जोड़ने, पैटर्न खोजने और अन्वेषकों की सहायता के लिए सुरक्षित इंटेलिजेंस वर्कस्पेस।', evidenceFirst:'साक्ष्य-प्रथम जांच', graphPowered:'ग्राफ आधारित लिंकेज विश्लेषण', auditableByDesign:'ऑडिट के लिए बनाया गया', prototypeFooter:'नेत्ररक्षक • SIH 2026 प्रोटोटाइप', versionFooter:'v0.1 • साक्ष्य अखंडता सक्षम', weeklyChange:'+8.4% इस सप्ताह', hashVerified:'हैश सत्यापित', entityMergeReview:'इकाई मर्ज समीक्षा', assigned:'ए. शर्मा को सौंपा गया', newLinkDetected:'नया लिंक मिला', linkedAccount:'खाता •• 9130 ↔ अर्जुन पवार', datasetManifest:'डेटासेट मेनिफेस्ट', demoBatch:'सिंथेटिक डेमो बैच v0.3', lastVerifiedTime:'अंतिम सत्यापन 09:42 IST', riskDates:['15 अगस्त','22 अगस्त','29 अगस्त','05 सितंबर','12 सितंबर'], refreshed:'जोखिम संकेत रीफ्रेश हुआ' },
  mr: { workspace:'कार्य क्षेत्र', governance:'प्रशासन', liveAudit:'लाइव्ह ऑडिट स्ट्रीम', riskPulse:'जोखीम संकेत', last30:'मागील 30 दिवस', sortBy:'क्रमवारी', entitiesCount:'संस्था', prototypeEnvironment:'प्रोटोटाइप वातावरण', priorityReview:'2 उच्च प्राधान्य · 1 पुनरावलोकन', sourceTypes:'7 स्रोत प्रकारांमध्ये', lastVerified:'शेवटचे सत्यापन 09:42 IST', operationMonsoon:'ऑपरेशन मॉन्सून', caseLocation:'पुणे • महाराष्ट्र • 18 जोडलेल्या संस्था', networkConfidence:'नेटवर्क विश्वास', linkageAnalysis:'लिंकेज विश्लेषण • ऑपरेशन मॉन्सून', documentIntelligence:'दस्तऐवज इंटेलिजन्स • NCRB वर्कफ्लो', uploadWorkflow:'जबाबदार चेन ऑफ कस्टडीसह अपलोड, फिंगरप्रिंट, एक्स्ट्रॅक्ट, पुनरावलोकन आणि सेव्ह करा.', fingerprintStep:'फिंगरप्रिंट', extractStep:'काढा', reviewStep:'पुनरावलोकन', commitStep:'कमिट', sha256:'SHA-256', ocrAdapter:'OCR अडॅप्टर', officerConfirmation:'अधिकारी पुष्टी', auditLedger:'ऑडिट + लेजर', reviewRequired:'कमिटपूर्वी पुनरावलोकन आवश्यक आहे', importManifest:'मॅनिफेस्ट आयात करा', sourceCatalogue:'प्रशासन • स्रोत सूची', sourceProvenance:'प्रत्येक रेकॉर्डमध्ये स्रोत वर्ग, प्रोव्हेनेन्स आणि अखंडता स्थिती आहे.', batchVerified:'शेवटचे बॅच सत्यापन: 09:42 IST', permissionedReady:'परवानाधारक तैनातीसाठी तयार', anomalousExports:'0 असामान्य एक्सपोर्ट', accessControls:'प्रवेश नियंत्रण', investigatorProfile:'तपासनीस प्रोफाइल', responsibleAI:'जबाबदार AI नियंत्रणे', defaultLanguage:'डीफॉल्ट भाषा', dataEnvironment:'डेटा वातावरण', mfaEnabled:'MFA सक्षम' },
  gu: { workspace:'વર્કસ્પેસ', governance:'ગવર્નન્સ', liveAudit:'લાઇવ ઓડિટ સ્ટ્રીમ', riskPulse:'જોખમ સંકેત', last30:'છેલ્લા 30 દિવસ', sortBy:'ક્રમમાં ગોઠવો', entitiesCount:'એન્ટિટી', prototypeEnvironment:'પ્રોટોટાઇપ વાતાવરણ', priorityReview:'2 ઉચ્ચ પ્રાથમિકતા · 1 સમીક્ષા', sourceTypes:'7 સ્રોત પ્રકારોમાં', lastVerified:'છેલ્લી ચકાસણી 09:42 IST', operationMonsoon:'ઓપરેશન મોનસૂન', caseLocation:'પુણે • મહારાષ્ટ્ર • 18 જોડાયેલી એન્ટિટી', networkConfidence:'નેટવર્ક વિશ્વાસ', linkageAnalysis:'લિંકેજ વિશ્લેષણ • ઓપરેશન મોનસૂન', documentIntelligence:'દસ્તાવેજ ઇન્ટેલિજન્સ • NCRB વર્કફ્લો', uploadWorkflow:'જવાબદાર ચેન ઓફ કસ્ટડી સાથે અપલોડ, ફિંગરપ્રિન્ટ, એક્સ્ટ્રેક્ટ, સમીક્ષા અને સેવ કરો.', fingerprintStep:'ફિંગરપ્રિન્ટ', extractStep:'કાઢો', reviewStep:'સમીક્ષા', commitStep:'કમિટ', sha256:'SHA-256', ocrAdapter:'OCR એડેપ્ટર', officerConfirmation:'અધિકારી પુષ્ટિ', auditLedger:'ઓડિટ + લેજર', reviewRequired:'કમિટ પહેલાં સમીક્ષા જરૂરી છે', importManifest:'મેનિફેસ્ટ આયાત કરો', sourceCatalogue:'ગવર્નન્સ • સ્રોત સૂચિ', sourceProvenance:'દરેક રેકોર્ડમાં સ્રોત વર્ગ, પ્રોવેનેન્સ અને અખંડિતતા સ્થિતિ છે.', batchVerified:'છેલ્લી બેચ ચકાસણી: 09:42 IST', permissionedReady:'પરમિશન્ડ ડિપ્લોયમેન્ટ માટે તૈયાર', anomalousExports:'0 અસામાન્ય એક્સપોર્ટ', accessControls:'ઍક્સેસ નિયંત્રણ', investigatorProfile:'તપાસકર્તા પ્રોફાઇલ', responsibleAI:'જવાબદાર AI નિયંત્રણો', defaultLanguage:'ડિફૉલ્ટ ભાષા', dataEnvironment:'ડેટા વાતાવરણ', mfaEnabled:'MFA સક્ષમ' }
};
Object.entries(extraTranslations).forEach(([locale, values]) => Object.assign(translations[locale], values));
Object.assign(translations.en, { documentReceived:'Document received', officerActor:'Officer A. Sharma', hashGenerated:'SHA-256 generated', browserCrypto:'Browser cryptography', ocrExtraction:'OCR extraction', adapterNotConnected:'Adapter not connected', pending:'Pending', firNumber:'FIR number', policeStation:'Police station', district:'District', incidentDate:'Incident date', sections:'Sections', namedEntities:'Named entities', extractedPending:'6 extracted · 2 pending review', sourceIntegrity:'FIR + CDR + synthetic', documentCount:'No document selected' });
Object.assign(translations.hi, { documentReceived:'दस्तावेज़ प्राप्त', officerActor:'अधिकारी ए. शर्मा', hashGenerated:'SHA-256 बनाया गया', browserCrypto:'ब्राउज़र क्रिप्टोग्राफी', ocrExtraction:'OCR एक्सट्रैक्शन', adapterNotConnected:'एडाप्टर कनेक्ट नहीं है', pending:'लंबित', firNumber:'एफआईआर नंबर', policeStation:'पुलिस स्टेशन', district:'जिला', incidentDate:'घटना की तारीख', sections:'धाराएं', namedEntities:'नामित इकाइयां', extractedPending:'6 निकाली गईं · 2 समीक्षा लंबित', sourceIntegrity:'एफआईआर + CDR + सिंथेटिक', documentCount:'कोई दस्तावेज़ नहीं चुना' });
const accessibilityTranslations = {
  en:{accessibility:'Accessibility',decreaseText:'Decrease text size',resetText:'Reset text size',increaseText:'Increase text size',collapseSidebar:'Collapse navigation',expandSidebar:'Expand navigation',manualEntry:'Manual FIR entry',scannedUpload:'Scanned FIR upload',caseDetails:'Case details',personDetails:'Subject details',evidence:'Evidence',saveDraft:'Save draft',addEvidence:'Add evidence',evidenceType:'Evidence type',evidenceDescription:'Evidence description',subjectName:'Subject name',alias:'Alias / known as',dob:'Date of birth',address:'Address',phone:'Phone number',vehicle:'Vehicle number',bank:'Bank / wallet identifier',incidentSummary:'Incident summary',reportingOfficer:'Reporting officer',saveCase:'Save FIR case',draftSaved:'FIR draft saved locally',caseSaved:'FIR case saved for review',manualEntryHelp:'Enter case facts, subject identifiers, and evidence for officer review.',documentEvidence:'Document',deviceEvidence:'Device',financialEvidence:'Financial record',witnessEvidence:'Witness statement',draft:'Draft',removeEvidence:'Remove evidence'},
  hi:{accessibility:'सुलभता',decreaseText:'अक्षर छोटे करें',resetText:'अक्षर रीसेट करें',increaseText:'अक्षर बड़े करें',collapseSidebar:'नेविगेशन बंद करें',expandSidebar:'नेविगेशन खोलें',manualEntry:'मैनुअल एफआईआर प्रविष्टि',scannedUpload:'स्कैन की गई एफआईआर',caseDetails:'केस विवरण',personDetails:'विषय विवरण',evidence:'साक्ष्य',saveDraft:'ड्राफ्ट सेव करें',addEvidence:'साक्ष्य जोड़ें',evidenceType:'साक्ष्य प्रकार',evidenceDescription:'साक्ष्य विवरण',subjectName:'विषय का नाम',alias:'उपनाम / अन्य नाम',dob:'जन्म तिथि',address:'पता',phone:'फोन नंबर',vehicle:'वाहन नंबर',bank:'बैंक / वॉलेट पहचान',incidentSummary:'घटना सारांश',reportingOfficer:'रिपोर्टिंग अधिकारी',saveCase:'एफआईआर केस सेव करें',draftSaved:'एफआईआर ड्राफ्ट स्थानीय रूप से सेव हुआ',caseSaved:'एफआईआर केस समीक्षा के लिए सेव हुआ',manualEntryHelp:'अधिकारी की समीक्षा के लिए केस तथ्य, विषय पहचान और साक्ष्य दर्ज करें।',documentEvidence:'दस्तावेज़',deviceEvidence:'डिवाइस',financialEvidence:'वित्तीय रिकॉर्ड',witnessEvidence:'गवाह का बयान',draft:'ड्राफ्ट',removeEvidence:'साक्ष्य हटाएं'},
  mr:{accessibility:'सुलभता',decreaseText:'मजकूर लहान करा',resetText:'मजकूर रीसेट करा',increaseText:'मजकूर मोठा करा',collapseSidebar:'नेव्हिगेशन बंद करा',expandSidebar:'नेव्हिगेशन उघडा',manualEntry:'मॅन्युअल FIR नोंद',scannedUpload:'स्कॅन केलेली FIR',caseDetails:'केस तपशील',personDetails:'विषय तपशील',evidence:'पुरावा',saveDraft:'ड्राफ्ट सेव्ह करा',addEvidence:'पुरावा जोडा',evidenceType:'पुराव्याचा प्रकार',evidenceDescription:'पुराव्याचे वर्णन',subjectName:'विषयाचे नाव',alias:'उपनाव / इतर नाव',dob:'जन्मतारीख',address:'पत्ता',phone:'फोन नंबर',vehicle:'वाहन क्रमांक',bank:'बँक / वॉलेट ओळख',incidentSummary:'घटनेचा सारांश',reportingOfficer:'रिपोर्टिंग अधिकारी',saveCase:'FIR केस सेव्ह करा',draftSaved:'FIR ड्राफ्ट स्थानिकरित्या सेव्ह झाला',caseSaved:'FIR केस पुनरावलोकनासाठी सेव्ह झाला',manualEntryHelp:'अधिकारी पुनरावलोकनासाठी केस तथ्ये, विषय ओळख आणि पुरावा भरा.',documentEvidence:'दस्तऐवज',deviceEvidence:'डिव्हाइस',financialEvidence:'आर्थिक नोंद',witnessEvidence:'साक्षीदाराचे निवेदन',draft:'ड्राफ्ट',removeEvidence:'पुरावा काढा'},
  gu:{accessibility:'ઍક્સેસિબિલિટી',decreaseText:'ટેક્સ્ટ નાનું કરો',resetText:'ટેક્સ્ટ રીસેટ કરો',increaseText:'ટેક્સ્ટ મોટું કરો',collapseSidebar:'નેવિગેશન બંધ કરો',expandSidebar:'નેવિગેશન ખોલો',manualEntry:'મેન્યુઅલ FIR એન્ટ્રી',scannedUpload:'સ્કેન કરેલી FIR',caseDetails:'કેસ વિગતો',personDetails:'વિષય વિગતો',evidence:'પુરાવો',saveDraft:'ડ્રાફ્ટ સાચવો',addEvidence:'પુરાવો ઉમેરો',evidenceType:'પુરાવાનો પ્રકાર',evidenceDescription:'પુરાવાનું વર્ણન',subjectName:'વિષયનું નામ',alias:'ઉપનામ / અન્ય નામ',dob:'જન્મ તારીખ',address:'સરનામું',phone:'ફોન નંબર',vehicle:'વાહન નંબર',bank:'બેંક / વૉલેટ ઓળખ',incidentSummary:'ઘટનાનો સારાંશ',reportingOfficer:'રિપોર્ટિંગ અધિકારી',saveCase:'FIR કેસ સાચવો',draftSaved:'FIR ડ્રાફ્ટ સ્થાનિક રીતે સાચવાયો',caseSaved:'FIR કેસ સમીક્ષા માટે સાચવાયો',manualEntryHelp:'અધિકારી સમીક્ષા માટે કેસ તથ્યો, વિષય ઓળખ અને પુરાવો દાખલ કરો.',documentEvidence:'દસ્તાવેજ',deviceEvidence:'ડિવાઇસ',financialEvidence:'નાણાકીય રેકોર્ડ',witnessEvidence:'સાક્ષીનું નિવેદન',draft:'ડ્રાફ્ટ',removeEvidence:'પુરાવો દૂર કરો'}
};
Object.entries(accessibilityTranslations).forEach(([locale, values]) => Object.assign(translations[locale], values));
Object.assign(translations.en,{authFailed:'Unable to sign in. Check your credentials.',authNotConfigured:'Supabase is not configured; local demo session used.'});
Object.assign(translations.hi,{authFailed:'प्रवेश नहीं हो सका। अपने क्रेडेंशियल जांचें।',authNotConfigured:'Supabase कॉन्फ़िगर नहीं है; स्थानीय डेमो सत्र इस्तेमाल हुआ।'});
Object.assign(translations.mr,{authFailed:'प्रवेश करता आला नाही. तुमची क्रेडेन्शियल तपासा.',authNotConfigured:'Supabase कॉन्फिगर केलेले नाही; स्थानिक डेमो सत्र वापरले.'});
Object.assign(translations.gu,{authFailed:'સાઇન ઇન થઈ શક્યું નથી. તમારા ક્રેડેન્શિયલ તપાસો.',authNotConfigured:'Supabase ગોઠવાયેલું નથી; સ્થાનિક ડેમો સત્ર વપરાયું.'});
Object.assign(translations.en,{saveFailed:'The FIR could not be saved. Try again or check the database setup.'});
Object.assign(translations.hi,{saveFailed:'एफआईआर सेव नहीं हो सकी। फिर कोशिश करें या डेटाबेस सेटअप जांचें।'});
Object.assign(translations.mr,{saveFailed:'FIR सेव्ह करता आली नाही. पुन्हा प्रयत्न करा किंवा डेटाबेस सेटअप तपासा.'});
Object.assign(translations.gu,{saveFailed:'FIR સાચવી શકાયી નથી. ફરી પ્રયાસ કરો અથવા ડેટાબેસ સેટઅપ તપાસો.'});
Object.assign(translations.en,{influence:'Influence'});
Object.assign(translations.hi,{influence:'प्रभाव'});
Object.assign(translations.mr,{influence:'प्रभाव'});
Object.assign(translations.gu,{influence:'પ્રભાવ'});

const entities = [
  { id: 'e1', name: 'Arjun Pawar', local: 'अर्जुन पवार', type: 'Person', risk: 'high', degree: 18, recent: 92, city: 'Pune, Maharashtra', phone: '+91 98••• 4421', events: 14, x: 380, y: 230 },
  { id: 'e2', name: 'Meera Logistics', local: 'मीरा लॉजिस्टिक्स', type: 'Organization', risk: 'medium', degree: 12, recent: 70, city: 'Nashik, Maharashtra', phone: 'GSTN •••• 883', events: 8, x: 220, y: 130 },
  { id: 'e3', name: 'Rakesh Solanki', local: 'राकेश सोलंकी', type: 'Person', risk: 'high', degree: 15, recent: 84, city: 'Ahmedabad, Gujarat', phone: '+91 97••• 1098', events: 11, x: 580, y: 120 },
  { id: 'e4', name: 'MH-12-QR-7742', local: 'MH-12-QR-7742', type: 'Vehicle', risk: 'medium', degree: 8, recent: 58, city: 'Pune, Maharashtra', phone: 'Registered asset', events: 6, x: 175, y: 340 },
  { id: 'e5', name: 'FIR/2024/01983', local: 'FIR/2024/01983', type: 'FIR', risk: 'low', degree: 5, recent: 45, city: 'Pimpri-Chinchwad', phone: 'Pimpri PS', events: 4, x: 590, y: 350 },
  { id: 'e6', name: 'Account •• 9130', local: 'खाता •• 9130', type: 'Bank account', risk: 'high', degree: 10, recent: 75, city: 'Surat, Gujarat', phone: 'Banking identifier', events: 9, x: 390, y: 420 },
  { id: 'e7', name: 'Bhosari Industrial Area', local: 'भोसरी औद्योगिक क्षेत्र', type: 'Location', risk: 'low', degree: 6, recent: 39, city: 'Pune, Maharashtra', phone: 'Mapped location', events: 5, x: 90, y: 210 },
  { id: 'e8', name: 'Nitin Deshmukh', local: 'नितिन देशमुख', type: 'Person', risk: 'medium', degree: 9, recent: 67, city: 'Pune, Maharashtra', phone: '+91 91••• 2284', events: 7, x: 285, y: 260 },
  { id: 'e9', name: 'Kavya Transport Services', local: 'काव्या ट्रान्सपोर्ट', type: 'Organization', risk: 'low', degree: 7, recent: 52, city: 'Mumbai, Maharashtra', phone: 'GSTN •••• 417', events: 5, x: 120, y: 460 },
  { id: 'e10', name: '+91 99••• 7712', local: '+91 99••• 7712', type: 'Phone', risk: 'high', degree: 11, recent: 88, city: 'Mumbai, Maharashtra', phone: 'Telecom identifier', events: 10, x: 530, y: 235 },
  { id: 'e11', name: 'GJ-01-AB-9912', local: 'GJ-01-AB-9912', type: 'Vehicle', risk: 'low', degree: 5, recent: 43, city: 'Ahmedabad, Gujarat', phone: 'Registered asset', events: 3, x: 680, y: 120 },
  { id: 'e12', name: 'FIR/2025/00742', local: 'FIR/2025/00742', type: 'FIR', risk: 'medium', degree: 6, recent: 61, city: 'Ahmedabad East', phone: 'Vastrapur PS', events: 5, x: 670, y: 330 },
  { id: 'e13', name: 'Account •• 4401', local: 'खाता •• 4401', type: 'Bank account', risk: 'medium', degree: 8, recent: 72, city: 'Mumbai, Maharashtra', phone: 'Banking identifier', events: 6, x: 500, y: 455 },
  { id: 'e14', name: 'Surat Warehouse Cluster', local: 'સુરત વેરહાઉસ ક્લસ્ટર', type: 'Location', risk: 'medium', degree: 6, recent: 64, city: 'Surat, Gujarat', phone: 'Mapped location', events: 4, x: 330, y: 490 },
  { id: 'e15', name: 'Shakti Exports', local: 'शक्ति एक्सपोर्ट्स', type: 'Organization', risk: 'medium', degree: 8, recent: 69, city: 'Surat, Gujarat', phone: 'GSTN •••• 902', events: 7, x: 205, y: 395 },
  { id: 'e16', name: 'Priya Jadhav', local: 'प्रिया जाधव', type: 'Person', risk: 'low', degree: 5, recent: 36, city: 'Nashik, Maharashtra', phone: '+91 88••• 3202', events: 3, x: 45, y: 95 },
  { id: 'e17', name: 'DL-08-ZX-2811', local: 'DL-08-ZX-2811', type: 'Vehicle', risk: 'high', degree: 6, recent: 81, city: 'New Delhi', phone: 'Registered asset', events: 5, x: 555, y: 480 },
  { id: 'e18', name: 'FIR/2025/01428', local: 'FIR/2025/01428', type: 'FIR', risk: 'high', degree: 6, recent: 86, city: 'South Delhi', phone: 'Saket PS', events: 6, x: 650, y: 430 },
  { id: 'e19', name: 'Rohit Khan', local: 'रोहित खान', type: 'Person', risk: 'high', degree: 7, recent: 90, city: 'New Delhi', phone: '+91 90••• 1804', events: 8, x: 635, y: 250 },
  { id: 'e20', name: 'Jaipur Safehouse Area', local: 'जयपुर सेफहाउस क्षेत्र', type: 'Location', risk: 'medium', degree: 4, recent: 58, city: 'Jaipur, Rajasthan', phone: 'Mapped location', events: 3, x: 430, y: 80 },
  { id: 'e21', name: 'Mahadev Finserv', local: 'महादेव फिनसर्व', type: 'Organization', risk: 'low', degree: 4, recent: 31, city: 'Nagpur, Maharashtra', phone: 'GSTN •••• 155', events: 3, x: 60, y: 400 }
];
const edges = [['e1','e2'],['e1','e3'],['e1','e4'],['e1','e6'],['e2','e7'],['e2','e5'],['e3','e6'],['e3','e5'],['e4','e7'],['e5','e6'],['e6','e7'],['e2','e8'],['e8','e9'],['e9','e13'],['e13','e14'],['e14','e15'],['e3','e11'],['e11','e12'],['e12','e15'],['e16','e21'],['e8','e16'],['e17','e18'],['e18','e19'],['e19','e20'],['e6','e13'],['e12','e13'],['e15','e20'],['e10','e1'],['e10','e19']];
const riskColor = { high: '#c2415a', medium: '#d78b22', low: '#238b68' };
let state = { locale: localStorage.getItem('locale') || 'en', loggedIn: false, view: 'overview', query: '', sort: 'risk', type: 'all', selected: 'e1', file: null, fileHash: '', filePath: '', graphFullscreen: false, sidebarCollapsed: false, fontScale: 1, firMode: 'upload', manualEvidence: [] };
let sigmaInstance = null;
const t = (key) => (translations[state.locale] || translations.en)[key] || translations.en[key] || key;
const el = (tag, attrs = {}, children = []) => { const node = document.createElement(tag); Object.entries(attrs).forEach(([k,v]) => { if (k === 'class') node.className = v; else if (k === 'html') node.innerHTML = v; else if (k.startsWith('on') && typeof v === 'function') node[k] = v; else if (k === 'value') node.value = v; else if (k === 'selected' || k === 'checked' || k === 'disabled' || k === 'hidden') node[k] = Boolean(v); else node.setAttribute(k,v); }); children.forEach(c => node.append(c)); return node; };
const icon = (name) => ({shield:'◈', search:'⌕', grid:'▦', network:'◎', file:'▤', database:'◫', settings:'⚙', arrow:'→', check:'✓', lock:'▣', upload:'↑', expand:'⤢', close:'×', alert:'!', pulse:'◉'}[name] || '•');
function showToast(message) { document.querySelector('.app-toast')?.remove(); const toast = el('div', { class: 'app-toast' }, [icon('check'), message]); document.body.append(toast); setTimeout(() => toast.remove(), 2600); }

function langPicker() { const select = el('select',{class:'language-select','aria-label':t('language')}); [['en','English'],['hi','हिन्दी'],['mr','मराठी'],['gu','ગુજરાતી']].forEach(([v,l])=>{const o=el('option',{value:v},[l]); if(v===state.locale)o.selected=true; select.append(o)}); select.onchange=()=>{state.locale=select.value;localStorage.setItem('locale',state.locale);render()}; return select; }
function logo() { return el('div',{class:'brand'},[el('div',{class:'brand-mark'},[icon('shield')]),el('div',{},[el('strong',{},[t('product')]),el('span',{},[t('productSub')])])]); }
async function signInOfficer(form){const email=form.querySelector('input[type="email"]').value.trim();const password=form.querySelector('input[type="password"]').value;if(supabaseConfigured){const {error}=await supabase.auth.signInWithPassword({email,password});if(error){showToast(t('authFailed'));return;}state.loggedIn=true;render();return;}localStorage.setItem('demoSession','true');state.loggedIn=true;showToast(t('authNotConfigured'));render();}
async function signOutOfficer(){if(supabaseConfigured)await supabase.auth.signOut();localStorage.removeItem('demoSession');state.loggedIn=false;render();}
async function bootstrapAuth(){if(supabaseConfigured){const {data}=await supabase.auth.getSession();if(data.session){state.loggedIn=true;render();}supabase.auth.onAuthStateChange((_event,session)=>{const next=Boolean(session);if(next!==state.loggedIn){state.loggedIn=next;render();}});}else if(localStorage.getItem('demoSession')==='true'){state.loggedIn=true;render();}}
function renderLogin() { const root=document.querySelector('#app'); root.innerHTML=''; const brandPanel=el('section',{class:'login-brand-panel'},[logo(),el('div',{class:'hero-copy'},[el('div',{class:'eyebrow'},[icon('lock'),t('restricted')]),el('h1',{},[t('heroTitle')]),el('p',{},[t('heroBody')]),el('div',{class:'hero-points'},[['shield',t('evidenceFirst')],['network',t('graphPowered')],['check',t('auditableByDesign')]].map(([i,x])=>el('div',{},[el('span',{class:'point-icon'},[icon(i)]),x])))]),el('span',{class:'authorized-badge'},[t('restricted')])]); const loginCard=el('section',{class:'login-card'},[el('div',{class:'login-card-top'},[langPicker()]),el('h2',{},[t('signInTitle')]),el('p',{class:'muted'},[t('signInBody')]),el('form',{class:'login-form'},[el('label',{},[t('email'),el('input',{type:'email',placeholder:'officer@ncrb.gov.in',required:true})]),el('label',{},[t('password'),el('input',{type:'password',placeholder:'••••••••',required:true})]),el('button',{class:'primary-btn',type:'submit'},[t('signIn'),el('span',{},[icon('arrow')])]),el('p',{class:'demo-hint'},[icon('alert'),t('demoHint')])]),el('div',{class:'login-footer'},[t('prototypeFooter'),t('versionFooter')])]); const page=el('main',{class:'login-page'},[el('div',{class:'login-surface'},[brandPanel,loginCard])]); root.append(page); page.querySelector('form').onsubmit=(e)=>{e.preventDefault();signInOfficer(e.currentTarget)}; }
function navItem(view, label, i) { const b=el('button',{class:`nav-item ${state.view===view?'active':''}`},[el('span',{class:'nav-icon'},[icon(i)]),el('span',{},[label])]); b.onclick=()=>{state.view=view;render()}; return b; }
function accessibilityControls(){const wrap=el('div',{class:'accessibility-controls'},[el('span',{class:'accessibility-label'},[t('accessibility')]),el('button',{class:'a11y-btn',title:t('decreaseText'),onclick:()=>setTextScale(-0.1)},['A−']),el('button',{class:'a11y-btn',title:t('resetText'),onclick:()=>setTextScale(0,true)},['A']),el('button',{class:'a11y-btn',title:t('increaseText'),onclick:()=>setTextScale(0.1)},['A+'])]);return wrap;}
function setTextScale(delta,reset=false){state.fontScale=reset?1:Math.min(1.25,Math.max(.9,state.fontScale+delta));document.documentElement.style.setProperty("--text-scale",String(state.fontScale));}
function appShell() { const root=document.querySelector('#app'); root.innerHTML=''; const topbar=el('header',{class:'topbar'},[el('div',{class:'topbar-brand'},[el('div',{class:'topbar-mark'},[icon('shield')]),el('div',{},[el('strong',{},['Netrakshak']),el('span',{},[t('productSub')])])]),el('div',{class:'top-actions'},[el('div',{class:'global-search'},[icon('search'),el('input',{placeholder:t('search'),value:state.query})]),langPicker(),el('div',{class:'topbar-officer'},[el('div',{class:'avatar'},['AS']),el('div',{},[el('strong',{},[t('officerName')]),el('span',{},[t('investigationUnit')])])]),el('button',{class:'topbar-btn',onclick:signOutOfficer},[t('logout')])])]); const sidebar=el('aside',{class:'sidebar'},[el('button',{class:'sidebar-toggle',title:state.sidebarCollapsed?t('expandSidebar'):t('collapseSidebar'),onclick:()=>{state.sidebarCollapsed=!state.sidebarCollapsed;render()}},[state.sidebarCollapsed?'▶':'◀']),el('div',{class:'nav-section-label'},[t('workspace')]),navItem('overview',t('command'),'grid'),navItem('network',t('network'),'network'),navItem('fir',t('fir'),'file'),el('div',{class:'nav-section-label'},[t('governance')]),navItem('sources',t('sources'),'database'),navItem('settings',t('settings'),'settings'),el('div',{class:'sidebar-bottom'},[el('div',{class:'profile-mini'},[el('div',{class:'avatar'},['AS']),el('div',{},[el('strong',{},[t('officerName')]),el('span',{},[t('investigationUnit')])])]),el('button',{class:'nav-item logout',onclick:signOutOfficer},[icon('close'),t('logout')])])]); const content=el('main',{class:'content'},[]); const shell=el('div',{class:`app-shell ${state.sidebarCollapsed?'sidebar-collapsed':''}`},[topbar,el('div',{class:'workspace'},[sidebar,el('div',{class:'main-area'},[content])])]); root.append(shell); shell.querySelector('.top-actions').prepend(accessibilityControls()); if(state.view==='overview') renderOverview(content); if(state.view==='network') renderNetwork(content); if(state.view==='fir') renderFIR(content); if(state.view==='sources') renderSources(content); if(state.view==='settings') renderSettings(content); const search=shell.querySelector('.global-search input'); search.oninput=(e)=>{state.query=e.target.value; updateSearchSuggestions(search)}; search.onfocus=()=>updateSearchSuggestions(search); search.onkeydown=(e)=>{if(e.key==='Enter'){e.preventDefault();state.view='network';render()}}; search.onblur=()=>setTimeout(()=>search.closest('.global-search')?.querySelector('.search-suggestions')?.remove(),160); }
function updateSearchSuggestions(input) { const box=input.closest('.global-search'); if(!box) return; box.querySelector('.search-suggestions')?.remove(); const query=input.value.trim().toLowerCase(); if(!query) return; const matches=entities.filter(entity=>[entity.name,entity.local,entity.type,entity.city,entity.phone].some(value=>String(value||'').toLowerCase().includes(query))).slice(0,7); const list=el('div',{class:'search-suggestions'},matches.length?matches.map(entity=>el('button',{class:'search-suggestion',type:'button',onclick:()=>{state.selected=entity.id;state.query='';state.view='network';render()}},[el('span',{class:'search-suggestion-name'},[entity.name]),el('span',{class:'search-suggestion-meta'},[`${entity.type} • ${entity.city}`])])):[el('div',{class:'search-empty'},[t('noResults')])]); box.append(list); }
function card(title, value, foot, cls='') { return el('div',{class:`metric-card ${cls}`},[el('div',{class:'metric-top'},[el('span',{class:'metric-label'},[title]),el('span',{class:'metric-spark'},[icon('pulse')])]),el('strong',{class:'metric-value'},[value]),el('span',{class:'metric-foot'},[foot])]); }
function renderOverview(c) { c.innerHTML=''; c.append(el('div',{class:'page-heading'},[el('div',{},[el('div',{class:'eyebrow blue'},[t('today')+' • 13 September 2026']),el('h1',{},[t('welcome')]),el('p',{class:'muted'},[t('briefing')])]),el('button',{class:'outline-btn',onclick:()=>{state.view='network';render()}},[icon('network'),t('viewNetwork')])]),el('div',{class:'notice-strip'},[el('span',{class:'notice-icon'},[icon('alert')]),el('div',{},[el('strong',{},[t('prototypeEnvironment')+' • '+t('synthetic')]),el('span',{class:'muted'},[t('sourceNote')])]),el('button',{class:'text-btn',onclick:()=>{state.view='sources';render()}},[t('viewAll'),icon('arrow')])]),el('div',{class:'metric-grid'},[card(t('alerts'),'03',t('priorityReview'),'metric-red'),card(t('entities'),String(entities.length),t('synthetic'),'metric-blue'),card(t('connections'),String(edges.length),t('sourceTypes'),'metric-green'),card(t('integrity'),'100%',t('lastVerified'),'metric-purple')]),el('div',{class:'dashboard-grid'},[recentPanel(),riskPanel()]),el('div',{class:'section-heading'},[el('h2',{},[t('activeCase')]),el('button',{class:'text-btn',onclick:()=>{state.view='network';render()}},[t('viewAll'),icon('arrow')])]),el('div',{class:'case-row'},[el('div',{class:'case-main'},[el('div',{class:'case-icon'},[icon('network')]),el('div',{},[el('strong',{},[t('operationMonsoon')]),el('span',{},[t('caseLocation')])])]),el('div',{class:'case-progress'},[el('div',{class:'progress-label'},[t('networkConfidence'),el('strong',{},['78%'])]),el('div',{class:'progress'},[el('span',{style:'width:78%'})])]),el('span',{class:'risk-badge high'},[t('high')]),el('button',{class:'icon-btn',onclick:()=>{state.view='network';render()}},[icon('arrow')])])); }
function recentPanel(){return el('section',{class:'panel'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('recent')]),el('span',{class:'muted'},[t('liveAudit')])]),el('span',{class:'live-dot'},['LIVE'])]),el('div',{class:'activity-list'},[['09:42','FIR/2024/01983',t('hashVerified'),'verified'],['09:31',t('entityMergeReview'),t('assigned'),'review'],['09:18',t('newLinkDetected'),t('linkedAccount'),'alert'],['08:55',t('datasetManifest'),t('demoBatch'),'imported']].map(([time,title,sub,kind])=>el('div',{class:'activity'},[el('span',{class:`activity-dot ${kind}`},[icon(kind==='alert'?'alert':'check')]),el('div',{},[el('strong',{},[title]),el('span',{},[sub])]),el('time',{},[time])])))]);}
function riskPanel(){return el('section',{class:'panel'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('riskPulse')]),el('span',{class:'muted'},[t('last30')])]),el('button',{class:'icon-btn',onclick:()=>showToast(t('refreshed'))},['•••'])]),el('div',{class:'risk-chart'},[el('div',{class:'chart-y'},['100','75','50','25','0'].map(x=>el('span',{},[x]))),el('div',{class:'chart-bars'},[35,48,42,65,55,80,68,90,72,82,60,75].map((h,i)=>el('i',{style:`height:${h}%`,class:i>8?'bar-hot':''}))),el('div',{class:'chart-x'},(t('riskDates')||translations.en.riskDates).map(x=>el('span',{},[x])))])]);}
function renderNetwork(c) {
  c.innerHTML = '';
  const analyticalEntities = graphMetrics(entities, edges);
  const filtered = analyticalEntities.filter(e => (state.type === 'all' || e.type === state.type) && (e.name.toLowerCase().includes(state.query.toLowerCase()) || e.local.includes(state.query)));
  const rank = { high: 0, medium: 1, low: 2 };
  const sorted = [...filtered].sort((a, b) => state.sort === 'name' ? a.name.localeCompare(b.name) : state.sort === 'connections' ? b.degree - a.degree : state.sort === 'recent' ? b.recent - a.recent : state.sort === 'influence' ? b.influence - a.influence : rank[a.risk] - rank[b.risk]);
  const n = el('div', { class: `network-workspace ${state.graphFullscreen ? 'fullscreen' : ''}` });
  const typeOptions = [['all', t('allTypes')], ...Array.from(new Set(entities.map(e => e.type))).map(x => [x, x])];
  const sortOptions = [['risk', t('risk')], ['connections', t('connectionsSort')], ['name', t('name')], ['recent', t('recent')], ['influence', t('influence')]];
  const typeSelect = el('select', { class: 'filter-select' }, typeOptions.map(([v, l]) => { const o = el('option', { value: v }, [l]); o.selected = v === state.type; return o; }));
  typeSelect.onchange = e => { state.type = e.target.value; render(); };
  const sortSelect = el('select', { class: 'filter-select' }, sortOptions.map(([v, l]) => { const o = el('option', { value: v }, [l]); o.selected = v === state.sort; return o; }));
  sortSelect.onchange = e => { state.sort = e.target.value; render(); };
  const fullscreen = el('button', { class: 'outline-btn', onclick: () => { state.graphFullscreen = !state.graphFullscreen; render(); } }, [icon('expand'), state.graphFullscreen ? t('exitFullscreen') : t('fullscreen')]);
  const firButton = el('button', { class: 'primary-btn small', onclick: () => { state.view = 'fir'; render(); } }, [icon('file'), t('reviewFIR')]);
  const heading = el('div', { class: 'page-heading compact' }, [el('div', {}, [el('div', { class: 'eyebrow blue' }, ['LINKAGE ANALYSIS • Operation Monsoon']), el('h1', {}, [t('network')]), el('p', { class: 'muted' }, [t('graphHint')])]), el('div', { class: 'heading-actions' }, [fullscreen, firButton])]);
  const toolbar = el('div', { class: 'network-toolbar' }, [el('div', { class: 'toolbar-group' }, [el('span', { class: 'toolbar-label' }, [t('filter')]), typeSelect]), el('div', { class: 'toolbar-group' }, [el('span', { class: 'toolbar-label' }, ['Sort by']), sortSelect]), el('span', { class: 'result-count' }, [sorted.length + ' entities'])]);
  const graph = el('section', { class: 'graph-panel' }, [graphContainer(sorted), el('div', { class: 'graph-legend' }, [['high', t('high')], ['medium', t('medium')], ['low', t('low')]].map(([r, l]) => el('span', {}, [el('i', { style: `background:${riskColor[r]}` }), l]))), el('div', { class: 'graph-controls' }, [el('button', { class: 'icon-btn', onclick: () => sigmaInstance?.getCamera().animatedZoom() }, ['＋']), el('button', { class: 'icon-btn', onclick: () => sigmaInstance?.getCamera().animatedUnzoom() }, ['−']), el('button', { class: 'icon-btn', onclick: () => sigmaInstance?.getCamera().animatedReset({ duration: 300 }) }, ['⌖'])])]);
  const entityAside = el('aside', { class: 'entity-panel' }, [selectedCard(), el('div', { class: 'entity-list-head' }, [el('h3', {}, [t('entities')]), el('span', { class: 'muted' }, [sorted.length + ' total'])]), el('div', { class: 'entity-list' }, sorted.map(e => entityListItem(e)))]);
  n.append(heading, toolbar, el('div', { class: 'network-grid' }, [graph, entityAside]));
  c.append(n);
  requestAnimationFrame(() => mountSigma(sorted));
}

function graphContainer(sorted) {
  return el('div', { class: 'sigma-container', 'data-graph-count': String(sorted.length) });
}

function mountSigma(sorted) {
  const container = document.querySelector('.sigma-container');
  if (!container) return;
  sigmaInstance?.kill();
  const graph = new Graph();
  sorted.forEach((entity, index) => {
    const angle = (index / Math.max(sorted.length, 1)) * Math.PI * 2;
    const radius = 0.25 + (index % 3) * 0.12;
    graph.addNode(entity.id, {
      label: entity.name,
      x: entity.x / 700 - 0.5 || Math.cos(angle) * radius,
      y: entity.y / 520 - 0.5 || Math.sin(angle) * radius,
      size: 7 + entity.degree * 0.75,
      color: riskColor[entity.risk],
      risk: entity.risk,
      entityId: entity.id,
    });
  });
  edges.forEach(([source, target]) => {
    if (graph.hasNode(source) && graph.hasNode(target) && !graph.hasEdge(source, target)) graph.addEdge(source, target, { color: '#cbd8e8', size: 1.5, type: 'line' });
  });
  sigmaInstance = new Sigma(graph, container, {
    renderLabels: true,
    labelFont: 'DM Sans',
    labelSize: 12,
    labelColor: { color: '#162b47' },
    defaultNodeColor: '#0d5bd7',
    defaultEdgeColor: '#cbd8e8',
    minCameraRatio: 0.2,
    maxCameraRatio: 5,
    allowInvalidContainer: true,
  });
  sigmaInstance.on('clickNode', ({ node }) => { state.selected = node; render(); });
}
function graphSvg(sorted){const visible=new Set(sorted.map(e=>e.id)); const svg=el('svg',{class:'graph-svg',viewBox:'0 0 700 520',role:'img','aria-label':t('network')}); edges.forEach(([a,b])=>{if(!visible.has(a)||!visible.has(b))return;const x=entities.find(e=>e.id===a),y=entities.find(e=>e.id===b);svg.append(el('line',{x1:x.x,y1:x.y,x2:y.x,y2:y.y,class:'edge'}))}); sorted.forEach(e=>{const g=el('g',{class:`node ${state.selected===e.id?'selected':''}`});g.append(el('circle',{cx:e.x,cy:e.y,r:13+e.degree*.85,fill:riskColor[e.risk],opacity:'.16',class:'node-halo'}),el('circle',{cx:e.x,cy:e.y,r:7+e.degree*.25,fill:riskColor[e.risk],class:'node-core'}),el('text',{x:e.x,y:e.y+34,'text-anchor':'middle'},[e.name.length>18?e.name.slice(0,17)+'…':e.name]));g.onclick=()=>{state.selected=e.id;render()};svg.append(g)});return svg;}
function selectedCard(){const e=entities.find(x=>x.id===state.selected)||entities[0];return el('div',{class:'selected-card'},[el('div',{class:'selected-top'},[el('span',{class:'entity-type'},[e.type]),el('span',{class:`risk-badge ${e.risk}`},[t(e.risk)])]),el('h2',{},[e.name]),el('p',{class:'muted'},[e.city]),el('div',{class:'selected-stats'},[[t('connectionsSort'),e.degree],[t('linkedEvents'),e.events],[t('recent'),e.recent+'%']].map(([a,b])=>el('div',{},[el('strong',{},[b]),el('span',{},[a])]))),el('div',{class:'detail-row'},[el('span',{},[t('source')]),el('strong',{},['FIR + CDR + synthetic'])]),el('div',{class:'detail-row'},[el('span',{},[t('confidence')]),el('strong',{},['91%'])]),el('button',{class:'outline-btn full',onclick:()=>showToast(`${e.name} evidence trail opened`)},[t('evidenceTrail'),icon('arrow')])]);}
function entityListItem(e){const b=el('button',{class:`entity-row ${state.selected===e.id?'selected':''}`},[el('span',{class:'entity-avatar',style:`background:${riskColor[e.risk]}18;color:${riskColor[e.risk]}`},[e.name.slice(0,1)]),el('span',{class:'entity-row-name'},[el('strong',{},[e.name]),el('small',{},[e.type])]),el('span',{class:'row-degree'},[e.degree]),el('span',{class:`risk-dot ${e.risk}`})]);b.onclick=()=>{state.selected=e.id;render()};return b;}
function renderFIR(c){
  c.innerHTML='';
  const modeBar=el('div',{class:'fir-mode-bar'},[
    el('span',{class:'section-label'},[t('caseDetails')]),
    el('div',{class:'mode-buttons'},[
      el('button',{class:`mode-button ${state.firMode==='upload'?'active':''}`,onclick:()=>{state.firMode='upload';render()}},[icon('upload'),t('scannedUpload')]),
      el('button',{class:`mode-button ${state.firMode==='manual'?'active':''}`,onclick:()=>{state.firMode='manual';render()}},[icon('file'),t('manualEntry')])
    ])
  ]);
  c.append(el('div',{class:'page-heading'},[el('div',{},[el('div',{class:'eyebrow blue'},[t('documentIntelligence')]),el('h1',{},[t('fir')]),el('p',{class:'muted'},[t('uploadWorkflow')])]),el('span',{class:'secure-pill'},[icon('lock'),t('secure')])]),modeBar);
  if(state.firMode==='manual') c.append(manualFIRPanel());
  else c.append(uploadFIRPanel());
}
function uploadFIRPanel(){return el('div',{class:'fir-grid'},[el('section',{class:'panel upload-panel'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('uploadTitle')]),el('span',{class:'muted'},[t('uploadBody')])])]),uploadBox(),el('div',{class:'workflow'},[['01',t('fingerprintStep'),t('sha256')],['02',t('extractStep'),t('ocrAdapter')],['03',t('reviewStep'),t('officerConfirmation')],['04',t('commitStep'),t('auditLedger')]].map(([n,a,b],i)=>el('div',{class:`workflow-step ${state.fileHash&&i===0?'done':''}`},[el('span',{},[n]),el('strong',{},[a]),el('small',{},[b])])))]),el('section',{class:'panel audit-panel'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('auditTitle')]),el('span',{class:'muted'},[t('auditBody')])]),el('span',{class:'verified-pill'},[icon('check'),t('verified')])]),el('div',{class:'audit-chain'},[['09:42 IST',t('documentReceived'),t('officerActor'),'hash'],['09:42 IST',t('hashGenerated'),t('browserCrypto'),'hash'],[t('pending'),t('ocrExtraction'),t('adapterNotConnected'),'pending']].map(([time,a,b,k])=>el('div',{class:'audit-event'},[el('div',{class:`audit-marker ${k}`},[k==='pending'?'…':icon('check')]),el('div',{},[el('strong',{},[a]),el('span',{},[b])]),el('time',{},[time])]))),el('div',{class:'hash-box'},[el('span',{},[t('fingerprint')]),el('code',{},[state.fileHash||'—'])])])]),el('div',{class:'panel draft-panel'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('reviewDraft')]),el('span',{class:'muted'},[t('reviewRequired')])]),el('span',{class:'draft-status'},[state.fileHash?'READY FOR REVIEW':t('noFile')])]),el('div',{class:'draft-grid'},[[t('firNumber'),'FIR/2024/01983'],[t('policeStation'),'Pimpri Police Station'],[t('district'),'Pune, Maharashtra'],[t('incidentDate'),'18 August 2024'],[t('sections'),'IPC 420 · 468 · 471'],[t('namedEntities'),t('extractedPending')]].map(([a,b])=>el('label',{},[a,el('input',{value:b,disabled:!state.fileHash})])))]);}
async function hashText(value){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(bytes)).map(b=>b.toString(16).padStart(2,'0')).join('');}
async function saveManualFIR(){
  if(!supabaseConfigured){showToast(t('authNotConfigured'));return;}
  const form=document.querySelector('.manual-form');
  const value=(name)=>form.querySelector(`[name="${name}"]`)?.value?.trim()||'';
  const {data:{user}}=await supabase.auth.getUser();
  if(!user){showToast(t('authFailed'));return;}
  const sections=value('sections').split(',').map(x=>x.trim()).filter(Boolean);
  const {data:fir,error:firError}=await supabase.from('fir_cases').insert({fir_number:value('firNumber'),police_station:value('policeStation'),district:value('district'),incident_date:value('incidentDate')||null,sections,incident_summary:value('incidentSummary'),extraction_status:'manual',created_by:user.id}).select('id').single();
  if(firError){showToast(t('saveFailed'));return;}
  const subjectName=value('subjectName');
  if(subjectName){
    const {data:entity,error:entityError}=await supabase.from('entities').insert({entity_type:'person',display_name:subjectName,aliases:value('alias')?[value('alias')]:[],identifiers:{dob:value('dob'),address:value('address'),phone:value('phone'),vehicle:value('vehicle'),bank:value('bank')},created_by:user.id}).select('id').single();
    if(entityError){showToast(t('saveFailed'));return;}
    await supabase.from('fir_entities').insert({fir_id:fir.id,entity_id:entity.id,involvement:'subject'});
  }
  for(const item of state.manualEvidence){let storagePath=null;let sha256=null;if(item.file){const buffer=await item.file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',buffer);sha256=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');const upload=await uploadPrivateEvidence({supabase,file:item.file,userId:user.id,sha256});if(upload.error){showToast(t('saveFailed'));return;}storagePath=upload.path;}const {error}=await supabase.from('evidence_items').insert({fir_id:fir.id,evidence_type:item.type,description:item.description,storage_path:storagePath,sha256,created_by:user.id});if(error){showToast(t('saveFailed'));return;}}
  const eventPayload=JSON.stringify({action:'fir.created',firId:fir.id,actor:user.id,at:new Date().toISOString()});
  const eventHash=await hashText(eventPayload);
  await supabase.from('audit_events').insert({actor_id:user.id,action:'fir.created',resource_type:'fir_case',resource_id:fir.id,change_summary:{firNumber:value('firNumber'),evidenceCount:state.manualEvidence.length},event_hash:eventHash});
  state.manualEvidence=[];
  showToast(t('caseSaved'));
  render();
}
function manualField(label,key,attrs={}){return el('label',{class:`manual-field ${attrs.wide?'wide':''}`},[label,el('input',{...attrs,name:key,wide:undefined,placeholder:attrs.placeholder||label})]);}
function manualFIRPanel(){
  const fields=el('div',{class:'manual-grid'},[
    manualField(t('firNumber'),'firNumber',{type:'text'}),manualField(t('policeStation'),'policeStation',{type:'text'}),
    manualField(t('district'),'district',{type:'text'}),manualField(t('incidentDate'),'incidentDate',{type:'date'}),
    manualField(t('sections'),'sections',{type:'text'}),manualField(t('reportingOfficer'),'reportingOfficer',{type:'text'}),
    manualField(t('subjectName'),'subjectName',{type:'text'}),manualField(t('alias'),'alias',{type:'text'}),
    manualField(t('dob'),'dob',{type:'date'}),manualField(t('phone'),'phone',{type:'tel'}),
    manualField(t('vehicle'),'vehicle',{type:'text'}),manualField(t('bank'),'bank',{type:'text'}),
    manualField(t('address'),'address',{type:'text',wide:true}),
    el('label',{class:'manual-field wide'},[t('incidentSummary'),el('textarea',{name:'incidentSummary',rows:'4',placeholder:t('incidentSummary')})])
  ]);
  const evidenceInput=el('div',{class:'evidence-entry'},[el('select',{},[el('option',{value:'document'},[t('documentEvidence')]),el('option',{value:'device'},[t('deviceEvidence')]),el('option',{value:'financial'},[t('financialEvidence')]),el('option',{value:'witness'},[t('witnessEvidence')])]),el('input',{placeholder:t('evidenceDescription')}),el('label',{class:'outline-btn evidence-file-picker'},[t('browse'),el('input',{type:'file',accept:'image/*,.pdf,.doc,.docx',hidden:true})]),el('button',{class:'outline-btn',onclick:()=>{const type=evidenceInput.querySelector('select').value;const description=evidenceInput.querySelector('input[placeholder]').value.trim();const file=evidenceInput.querySelector('input[type="file"]').files[0]||null;if(!description&&!file)return;state.manualEvidence.push({type,description:description||file.name,file});render()}},[icon('plus'),t('addEvidence')])]);
  const evidenceList=el('div',{class:'evidence-list'},state.manualEvidence.map((item,index)=>el('div',{class:'evidence-item'},[el('span',{class:'evidence-type'},[item.type]),el('span',{},[item.file?`${item.description} • ${item.file.name}`:item.description]),el('button',{class:'evidence-remove',title:t('removeEvidence'),onclick:()=>{state.manualEvidence.splice(index,1);render()}},['×'])])));
  return el('section',{class:'panel manual-form'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('manualEntry')]),el('span',{class:'muted'},[t('manualEntryHelp')])]),el('span',{class:'draft-status'},[t('draft')])]),el('div',{class:'manual-section'},[el('div',{class:'section-label'},[t('caseDetails')]),fields]),el('div',{class:'manual-section'},[el('div',{class:'section-label'},[t('evidence')]),evidenceInput,evidenceList]),el('div',{class:'manual-actions'},[el('button',{class:'outline-btn',onclick:()=>showToast(t('draftSaved'))},[t('saveDraft')]),el('button',{class:'primary-btn',onclick:saveManualFIR},[icon('check'),t('saveCase')])])]);
}
function uploadBox(){const box=el('div',{class:`upload-box ${state.fileHash?'has-file':''}`},[el('div',{class:'upload-icon'},[icon('upload')]),el('strong',{},[state.file?state.file.name:t('noFile')]),el('span',{},[state.fileHash?state.fileHash.slice(0,22)+'…':t('uploadBody')]),el('label',{class:'outline-btn'},[t('browse'),el('input',{type:'file',accept:'image/*,.pdf',hidden:true})])]);box.querySelector('input').onchange=async(e)=>{const file=e.target.files[0];if(!file)return;state.file=file;const buffer=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',buffer);state.fileHash=Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');if(supabaseConfigured){const {data:{user}}=await supabase.auth.getUser();const result=await uploadPrivateEvidence({supabase,file,userId:user?.id,sha256:state.fileHash});state.filePath=result.path||'';}render()};return box;}
function renderSources(c){c.innerHTML='';c.append(el('div',{class:'page-heading'},[el('div',{},[el('div',{class:'eyebrow blue'},['GOVERNANCE • SOURCE CATALOGUE']),el('h1',{},[t('sources')]),el('p',{class:'muted'},['Every record has a declared source class, provenance, and integrity status.'])]),el('button',{class:'primary-btn',onclick:()=>{state.view='fir';render()}},[icon('upload'),'Import manifest'])]),el('div',{class:'source-grid'},[['NCRB Crime in India 2023','Official aggregate context','OGD India','live','National crime and women-safety indicators'],['Synthetic FIR fixtures','Prototype case-level graph','Netrakshak seed','synthetic','Indian names, stations, vehicles, accounts, and links'],['IBM AMLSim','Synthetic transaction patterns','Research dataset','live','Financial graph stress-testing and typology patterns'],['Elliptic Bitcoin Dataset','Labeled crypto graph','Research dataset','live','Licit/illicit wallet-network experiments'],['CIC-IDS2017','Labeled cyber flows','Research dataset','live','Attack and benign traffic pattern experiments'],['Audit ledger','Hash-linked local chain','Netrakshak integrity','verified','Document and batch fingerprint verification']].map(([a,b,cx,status,d])=>el('div',{class:'source-card'},[el('div',{class:'source-card-top'},[el('div',{class:'source-symbol'},[icon(status==='verified'?'check':status==='synthetic'?'file':'database')]),el('span',{class:`source-status ${status}`},[t(status)])]),el('h3',{},[a]),el('p',{class:'muted'},[b]),el('div',{class:'source-divider'}),el('span',{},[cx]),el('small',{},[d])]))),el('div',{class:'panel integrity-panel'},[el('div',{class:'panel-heading'},[el('div',{},[el('h3',{},[t('integrityChecks')]),el('span',{class:'muted'},['Last batch verification: 09:42 IST'])])]),el('div',{class:'integrity-items'},[['hashChain','Hash-linked event chain','24 events verified'],['ledger','Ledger anchor status','Ready for permissioned deployment'],['access','Access review','0 anomalous exports']].map(([a,b,d])=>el('div',{class:'integrity-item'},[el('span',{class:'integrity-check'},[icon('check')]),el('div',{},[el('strong',{},[a==='hashChain'?t('hashChain'):a==='ledger'?t('ledger'):'Access controls']),el('span',{},[b])]),el('strong',{class:'integrity-value'},[d])])))])); }
function renderSettings(c) {
  c.innerHTML = '';
  const profile = el('section', { class: 'panel' }, [el('h3', {}, ['Investigator profile']), el('div', { class: 'profile-large' }, [el('div', { class: 'avatar big' }, ['AS']), el('div', {}, [el('strong', {}, ['A. Sharma']), el('span', {}, ['Maharashtra State Investigation Unit']), el('span', { class: 'verified-text' }, [icon('check'), ' MFA enabled'])])]), el('div', { class: 'setting-row' }, ['Default language', langPicker()]), el('div', { class: 'setting-row' }, ['Data environment', el('span', { class: 'secure-pill' }, [t('synthetic')])])]);
  const controls = [['Human review required', 'Enabled for OCR, entity merges, and alerts'], ['Evidence provenance', 'Shown on every extracted field'], ['Model confidence threshold', '0.78 minimum for suggestions'], ['Sensitive export approval', 'Two-person review']].map(([a, b]) => el('div', { class: 'toggle-row' }, [el('div', {}, [el('strong', {}, [a]), el('span', {}, [b])]), el('span', { class: 'toggle on' }, ['✓'])]));
  const guardrails = el('section', { class: 'panel' }, [el('h3', {}, ['Responsible AI controls']), ...controls]);
  c.append(el('div', { class: 'page-heading' }, [el('div', {}, [el('div', { class: 'eyebrow blue' }, ['ADMINISTRATION']), el('h1', {}, [t('settings')]), el('p', { class: 'muted' }, ['Local prototype settings and responsible-AI guardrails.'])])]), el('div', { class: 'settings-grid' }, [profile, guardrails]));
}
function render(){state.loggedIn?appShell():renderLogin()}
render();
bootstrapAuth();
